on: ["push"]

jobs:
  test:
    runs-on: docker
    container:
      image: gradle:alpine

    steps:
      - name: test
        run: |
          ls | echo
          export GRADLE_USER_HOME=`pwd`/.gradle

