on: ["push"]

jobs:
  test:
    runs-on: docker
    container:
      image: gradle:alpine

    steps:
      - name: list
        run: ls -al /workspace/Schiriki

      - name: test
        run: |
          export GRADLE_USER_HOME=`pwd`/.gradle
