on: ["push"]

jobs:
  test:
    runs-on: docker
    container:
      image: ubuntu:latest

    steps:
      - uses: https://code.forgejo.org/actions/checkout@v3
      - name: list
        run: ls -al /workspace/Schiriki/GradleTest

      - name: test
        run: |
          export GRADLE_USER_HOME=`pwd`/.gradle
