name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Set Gradle home
      run: export GRADLE_USER_HOME=`pwd`/.gradle

    - name: Cache Java JDK
      id: cache-jdk
      uses: https://code.forgejo.org/actions/cache@v3
      with:
        path: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.10-7/x64
        key: ${{ runner.os }}-jdk-17
        restore-keys: ${{ runner.os }}-jdk-

    - name: Checkout sources
      uses: https://code.forgejo.org/actions/checkout@v4

    - name: Set up JDK 17
      if: ${{ steps.cache-jdk.outputs.cache-hit != 'true' }}
      uses: https://github.com/actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build project
      run: ./gradlew build --no-daemon

    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper      
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-      
