name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: https://code.forgejo.org/actions/checkout@v4

    - uses: https://github.com/actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: https://github.com/gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      run: ./gradlew build
