on: ["push"]

jobs:
  test:
    runs-on: docker
    container:
      image: gradle:alpine
    steps:
      - name: list
        run: ls -al /workspace/Schiriki/GradleTest

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: test
        run: |
          export GRADLE_USER_HOME=`pwd`/.gradle
          ./gradlew check
