name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: https://code.forgejo.org/actions/checkout@v4
    - name: Setup Gradle
      uses: https://gitea.com/gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew build
